-- ShareTrip initial schema (Postgres / Supabase)

CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY,
    fname TEXT NOT NULL,
    lname TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT,
    gender TEXT NOT NULL CHECK (gender IN ('Male', 'Female')),
    able_driver BOOLEAN NOT NULL DEFAULT TRUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES accounts(id),
    ride_type TEXT NOT NULL CHECK (ride_type IN ('offer', 'request')),
    roundtrip BOOLEAN NOT NULL DEFAULT FALSE,
    seats INTEGER NOT NULL DEFAULT 1,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    origin TEXT NOT NULL,
    destination TEXT NOT NULL,
    destination_state TEXT,
    ride_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    gender_preference TEXT NOT NULL DEFAULT 'No preference'
        CHECK (gender_preference IN ('Same gender only', 'No preference')),
    assigned_driver_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS driver_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id BIGINT NOT NULL REFERENCES rides(id) ON DELETE CASCADE,
    driver_user_id TEXT NOT NULL REFERENCES accounts(id),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'accepted', 'declined')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    responded_at TIMESTAMPTZ,
    UNIQUE (ride_id, driver_user_id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES accounts(id),
    ride_id BIGINT REFERENCES rides(id) ON DELETE CASCADE,
    offer_id BIGINT,
    kind TEXT NOT NULL,
    message TEXT NOT NULL,
    read_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS passengers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id BIGINT NOT NULL REFERENCES rides(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES accounts(id),
    party_size INTEGER NOT NULL DEFAULT 1 CHECK (party_size >= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (ride_id, user_id)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id BIGINT NOT NULL REFERENCES rides(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES accounts(id),
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id BIGINT NOT NULL REFERENCES rides(id) ON DELETE CASCADE,
    rated_user_id TEXT NOT NULL,
    rater_user_id TEXT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    role TEXT NOT NULL CHECK (role IN ('driver', 'passenger')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (ride_id, rated_user_id, rater_user_id)
);

CREATE INDEX IF NOT EXISTS idx_accounts_email ON accounts (email);
CREATE INDEX IF NOT EXISTS idx_rides_owner ON rides (owner_id);
CREATE INDEX IF NOT EXISTS idx_rides_start_date ON rides (start_date);
CREATE INDEX IF NOT EXISTS idx_passengers_ride ON passengers (ride_id);
CREATE INDEX IF NOT EXISTS idx_passengers_user ON passengers (user_id);
CREATE INDEX IF NOT EXISTS idx_comments_ride ON comments (ride_id);
CREATE INDEX IF NOT EXISTS idx_ratings_ride ON ratings (ride_id);
CREATE INDEX IF NOT EXISTS idx_driver_offers_ride ON driver_offers (ride_id);
CREATE INDEX IF NOT EXISTS idx_driver_offers_driver ON driver_offers (driver_user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications (user_id);
